#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\GeeimapController::first_page

login:
  path: /login
  controller: App\Controller\GeeimapController::login