#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\HomeController:index



login:
  path: /login
  controller: App\Controller\SecurityController::login

register:
  path: /register
  controller: App\Controller\SecurityController::register

applicant_page_show:
  path: /applicant/page/{id}
  controller: App\Controller\ApplicantPageController::show

formulaire:
  path: /student/formulaire
  controller: App\Controller\Student\FormulaireController::fillform