#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\HomeController:index

admission:
  path: /admission_index
  controller: App\Controller\Admission\AdmissionController:index

student:
  path: /student
  controller: App\Controller\Student\ResumePageController:index

login:
  path: /login
  controller: App\Controller\SecurityController::login

register:
  path: /register
  controller: App\Controller\SecurityController::register
