#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\HomeController:index

admission:
  path: /admission
  controller: App\Controller\Admission\AdmissionController:index

formulaire:
  path: /student/formulaire
  controller: App\Controller\Student\FormulaireController:fillform

login:
  path: /login
  controller: App\Controller\SecurityController::login

register:
  path: /register
  controller: App\Controller\SecurityController::register
